### PR TITLE
Re-tag /sunseteyebrow with the correct character name

### PR DESCRIPTION
**Pull request by JedTheKrampus**
Right now /sunseteyebrow is in the +starlight list and it really grinds my gears.

### CODE REVIEW

**Comment by Shugabuga** [comment]
Commit seems alright.

**Comment by JedTheKrampus** [comment]
That seems fine. I haven't actually built and tested this but it seems pretty straightforward that this shouldn't break anything. I'm A-OK with waiting for the release because that's what I do anyway.

**Comment by Shugabuga** [comment]
Code looks fine though. It's just the tag you swapped out. *Shoudn't* break anything.

**Comment by JedTheKrampus** [comment]
Closing this pull request since it's fixed in #44.

**Pull request closed without merging**
