### PR TITLE
Add more flags + flag help menu

### PR DESCRIPTION
**Pull request by Shugabuga**
This adds the following flags (aliases also listed):

**-blur** (blurs the image)
**-w** (rocks the image back and forth)
**-wobble** (-w alias)
**-rock** (-w alias)
**-s** (makes the image sepia)
**-sepia** (-s alias)
**-bw** (makes the image monochromatic)
**-mono** (-bw alias)

All filters work fine in Chrome and Firefox, as seen below:

Chrome Canary Preview
<br>
Firefox Developer Edition Preview

### CODE REVIEW

**Comment by Carson-Shook** [comment]
Tested, and all of them work on the latest version of Safari as well.

I do find the rock/wobble emote a little oddly specific. The code could be cleaned up a tad to be organized more like the rest of the CSS, but other than that, I think that they would make good editions. I have to say that blur is my favorite and I look forward to seeing it abused on the PLounge ;)

**Comment by Ajedi32** [comment]
It'd be great if we could start documenting these somewhere. As-is none of these flags are very discoverable. I don't believe there's any place in the repo to put documentation like that though at the moment...

**Comment by Rothera** [comment]
If it's abuse potential you're looking for, can I suggest making the blur a little less obvious? Just enough to make you wonder if you're imagining it or not. Up to you.

(And if we really love abuse potential, maybe we need to work out a way to make an emote in my comment modify the emote in the parent comment.)

Wrt documentation: There is some precedent for basic help with some links at the bottom of the search box. It's currently "help | bpm options". I think it would be a fairly small project to add a new tab for flags, then maybe change it to "search help | flags help | bpm options" or such.

**Comment by Shugabuga** [comment]
Ok. I made the blurs less intense. 

-blur changes

I also added the -b shorthand, but if you don't want it, I can remove it.

Wrt documentation: I've got the tabs thing covered. I already have a working version of it, but it still needs to be populated with text. Take a look:

bpm_flagtab_preview

Please note that the text in the preview above is just a placeholder, so please give me ideas on what to put there! I was thinking some basic instruction and a list of flags, but I'm sure you all have better ideas!

**Comment by Rothera** [comment]
Regarding shorthands: I'm somewhat against having aliases for these. I don't think they serve much practical purpose. Emotes traditionally had a few (often a grid one, a nice one, and sometimes some "secret" ones) but flag names are a lot less visible.

**Comment by Rothera** [comment]
Regarding content: just a reference would probably be good, with syntax examples. We do have actual HTML here, though, so you can include actual emotes. I'm not sure offhand how the rest of the addon will interact with emotes we put here (I *think* there is some special handling for the search box somewhere but I do not recall specifics) so please test that. The example emotes should probably be "normal" ones from /r/mylittlepony, but there's a lot of opportunity for humor here.

**Comment by Shugabuga** [comment]
One more note about shorthands: should the shorter (i.e. -b) flag be used or the longer (-blur) be used? 

And I'll take your ideas and put them into the `flags help` menu.

**Comment by Rothera** [comment]
I would favor the longer names, for sake of being more self-describing.

**Comment by Ajedi32** [comment]
Yeah, I second that. Definitely mention the shorter aliases, but go with the more descriptive names for the examples and such.

**Comment by Shugabuga** [comment]
Got it!

**Comment by Shugabuga** [comment]
This is what I've got for the `flags help` menu. Also, scrolling was enabled for this to work, but it doesn't look like anything was affected (unless you make the emote box too small, which graphical issues already arise).

I still need to fix a few bugs, especially the ones with the -m modifier. I also should neaten the code (the table code sticks out too much in `bpm-searchbox.js`.

bpm_flagtab_preview

**Comment by Rothera** [comment]
There's definitely a lower limit to how small you can make the box before a table layout won't work, but it would be nice if it looked ok at the "standard" size, or whatever BPM sets it to by default on a fresh install. Narrow the table a bit if necessary.

I'm not totally sold on a table design, at least not for all of them. I think `-in` and `-ar` would benefit from having a short paragraph to themselves, since it's otherwise difficult to demonstrate what they do. I would also suggest separately grouping the simple flips, the rotations, the color changes, and the slides; the slides should probably have a large area to themselves to show off with. `-m` is subtle and only works on a few emotes, so we might consider just including all of them.

I would also suggest randomizing the emotes a bit. (If we wanted to be especially silly we could randomize them every time the tab loads, but that's hardly necessary.)

One thing that is somewhat concerning is, for me at least, the fancy modifiers tend to make my browser max out a cpu core. Please try to check that this tab doesn't do anything like that if it isn't visible. I think the `display: none` should be enough, but worth checking.

I note that you have added a `bpflag-m-demo` and have copied a little bit of the original aura code. Why is this necessary? I note that some of the original `-m` code is actually still using `a[href]` selectors, which I think I will fix; is that related?

Something worth thinking about: BPM still has an option to disable extracss stuff. There's not much rhyme or reason to the split between `bpmotes.css` and `extracss-*.css` anymore and some of that should probably be rethought. At the moment I think the idea is that `bpmotes.css` includes flags that don't animate things, so you might move the color changing ones there. There's also a couple of extra flags there for text (blink, fonts) to think about, which may or may not even work right anymore.

**Comment by Shugabuga** [comment]
To respond to your points: 

> I think -in and -ar would benefit from having a short paragraph to themselves, since it's otherwise difficult to demonstrate what they do. I would also suggest separately grouping the simple flips, the rotations, the color changes, and the slides; the slides should probably have a large area to themselves to show off with. -m is subtle and only works on a few emotes, so we might consider just including all of them.

Ok. I can do that! Especially with `-slide`, you can tell that BPM's having issues with sliding them.

> I note that you have added a bpflag-m-demo and have copied a little bit of the original aura code. Why is this necessary?

For some reason, BPM won't correctly add the -m modifier to emotes inside the box, so this was something I tried to fix it. I agree: it needs to be fixed, not just for code neatness, but it's causing some bugs. This ***will*** be fixed, as it also bugs out `display:none`, leaving a random unicorn aura on the page when closed. 

> At the moment I think the idea is that bpmotes.css includes flags that don't animate things, so you might move the color changing ones there.

It looks like that is how things are set up. I notice that `-invert` is in there, as with some other flags. Also, any styling regarding the emote box is put into that file.

Expect another commit in the next 24 hours.

**Comment by Shugabuga** [comment]
Also, whilst trying to re-do the tab, I answered one of your questions about the tab menu I'm working on.

>One thing that is somewhat concerning is, for me at least, the fancy modifiers tend to make my browser max out a cpu core. Please try to check that this tab doesn't do anything like that if it isn't visible. I think the display: none should be enough, but worth checking.

Well the answer is...

-spin still spins

It does move in the background; `display:none` isn't enough.

However, I can't test if it is actually eating up CPU.

**Comment by Shugabuga** [comment]
I think I have got to something that is mostly stable and more organized. Take a look:

"flags help" tab preview

Also, I chose to omit the `-s1` through `-s15` speed modifiers, as with `-fast`, `-faster`, `-fastest`, `-slow`, `-slower`, and `-slowest`. In my opinion there's not a good way to demo them without taking up a lot of space.

**Comment by Rothera** [comment]
That's *really* nice. We're badly overdue for an update, so if you think it's good, I'll see about getting this in and released later tonight.

**Comment by Shugabuga** [comment]
Give me a little while. Doing some final checks and having some weird bug with the `-m` preview. It's not going away, even with `display:none`. I'll probably have it ready in 45 minutes.

**Comment by Rothera** [comment]
Take your time. Not like I'm in a hurry to tag three new subreddits.

**Comment by Shugabuga** [comment]
Ok!

**Comment by ByzantineFailure** [comment]
An easy place to find a listing and examples of the flags and more of them?  Plus from the discord end of things this looks like it will Just Work?

Much excite.

**Comment by Shugabuga** [comment]
I just did commit the fix I was talking about. Ready for pull!

Changes in Pull:
- Added documentation for flags in emote selector box
- Added `-blur`, `-mono`, '-sepia', '-wobble', and `-papyrus!`
- Fixed a bug causing `-comicsans!` to not display as Comic Sans on Macs

**Comment by Rothera** [comment]
Unfortunately my suspicions were correct; as long as the element exists on the page, and `display: none` is not enough to change this, Chrome chews 100% of a CPU core. Not quite releasable.

Probably will want to work out a way to add/remove the tab HTML on load. Will look into it tomorrow. Also I may remove the `-rock` alias.

Does `-m` animate correctly in Chrome?

**Comment by Shugabuga** [comment]
Yes, you can remove the `-rock` alias, and the `-m` modifier works *outside* of the emote selector box (it works fine in comments). However, I am using a little hack to make it work inside the emote selector (stitched an image together, uploaded to Reddit, and used the `img` tag).

And I may be wrong, but I think you were using `visibility:hidden` for the box. Could that be the issue? 

I'll likely see later if using `display:none` instead of `visibility:hidden` is viable for hiding the emote box.

**Comment by Shugabuga** [comment]
I *think* that I fixed the bug with the animations in the background. It seems to reduce CPU a bit on my computer, but I'll show you my Activity Monitor results:

Header
Control
Old Pull
Current Pull

This was done 10 seconds after page load. Also, sorry for the terrible alignment of the blue bars; it's meaningless and was a result of terrible screenshotting.

Does this fix the issue on your machine? My computer seems to perform fine, but your mileage seems to vary from mine.

**Comment by Shugabuga** [comment]
Ok, I just pushed another edit that I want your opinion on.

[Someone on /r/betterponymotes suggested](https://www.reddit.com/r/betterponymotes/comments/4k6uh8/update_betterponymotes_v66245_20160520/d3et0me) for the ability to modulate the intensity of the `-blur` modifier, so I decided to add `-blur1` through `-blur15` to change the blur intensity by 0.5 pixels/step. 

Here's what the look like. There is 15 of them, just like `-s1` - `-s15`. Normal `-blur` is equal to `-blur3` by the way.

blur modifiers


Should I keep this in, change some things, or remove it completely?

**Comment by Ajedi32** [comment]
Looks awesome! Could you update the flags help to mention that?

**Comment by Rothera** [comment]
I like it. Per my reddit comment, you might want to try testing with a big emote too (e.g. `/lpsign`), since the effect is quite a bit different than with small ones. What do you think of a set with a larger step like [0.5, 2.0, 3.5, 5.0, 6.5, 8.0, 9.5, 11.0] ?

**Comment by Shugabuga** [comment]
I will in just a second Ajedi! Just doing some minor tweaks with the actual CSS. 

And I like that set Typhos, will make the changes in just a second. It's also worth noting, the current `-blur` is 1.5px.

And Typhos, does the latest commit on this pull max out your cores? I think I fixed it, but my computer doesn't seem to lag as much as yours.

**Comment by Shugabuga** [comment]
Flags help updated, and also added the `-s#` modifiers in the grouping as `-blur#`.

bpm-updated-emotebox

**Comment by Rothera** [comment]
I observe that Chromium sits at about 25% while the flags help box is open, but close to idle otherwise. Looks good. I'll check Firefox later.

I suggest bumping the default `-blur` up to the 2.0px level, since it seems a bit odd to have an "extra" level that's not quite the same as any of the rest.

Some final(?) nitpicks:

* I'm not sure 0.5px actually works the same in Firefox and Chrome. It's subtle but noticeable in Firefox, but in Chrome I can't tell if it's actually working or not without zooming in. It shows up rather suddenly at 0.8px, so perhaps we should make that our lowest setting.
* Maybe move the `-in` and `-ar` docs to the top. Along with `-r` I think they are probably the most generally useful.

**Comment by Shugabuga** [comment]
I fixed the nitpicks and some other minor details to make sure everything is looking good. This is what it looks like in Reddit:

bpm-updated-emotebox2

Now, I found an issue with emote conversion and this menu. It is converting the example syntax, as seen below. Is there a way to prevent this (I could always use invisible characters, but users could always copy the syntax with the invisible character)?

google com

**Comment by ByzantineFailure** [comment]
@Rothera Do you plan on updating BPM immediately when this is merged in or do you plan on waiting until the next emote update?  That'll determine whether or not I release a new Discord version now or wait until this is merged in.

**Comment by Rothera** [comment]
I will probably wait.

**Comment by Rothera** [comment]
Are we happy with this?

**Comment by ByzantineFailure** [comment]
Changes look clean and good to me.

**Comment by Shugabuga** [comment]
Everything seems good, ready to pull!

**Changes in Pull:**
- Added documentation for flags in emote selector box
- Added `-blur` (and some modulators for it), `-mono`, `-sepia`, `-wobble`, and `-papyrus!`
- Fixed a bug causing `-comicsans!` to not display as Comic Sans on Macs.
- Fixed a bug in Firefox rendering `-!slide` and `-!shift` non-functional.

**Comment by Shugabuga** [comment]
Sorry for the inconvenience, but I found a typo in the `flags help` menu. I just fixed it, so everything should be fine now!

**Ready to pull (again!)**

**Comment by Rothera** [comment]
I've been away. Should release another update with this included sometime this weekend.

**Comment by Shugabuga** [comment]
Okay! Sounds good!

**Comment by Ajedi32** [comment]
:tada:

**Pull request merged**
