### PR TITLE
Tag Updates

### PR DESCRIPTION
**Pull request by nano23823**
This PR contains tag updates for several subreddits I help moderate (mainly). They are grouped into commits for each sub/character tag, hoped to assist in examination. It also fixes some tagging issues mentioned in the v66.259 release thread:

* Untagged Thunderlane
* Untagged Blossomforth
* The Sunset tagged `+starlightglimmer`

To fix one of my mistakes in r/sunsetshimmer, the stylesheet required an update, meaning BPM requires an update/extract before `checktags.py` returns clean for that sub (but I did verify that it will).

### CODE REVIEW

**Comment by Rothera** [comment]
Oh yeah, this thing. Biggest problem I had trying to merge this was it touched a lot of tags without me really knowing why. Primary aliases moved around and I felt obligated to check all of them, but that's an annoying process.

If I can scroll through it and it's just obvious changes then I won't question it.

**Comment by nano23823** [comment]
Ah, most of the +v shuffle was r/sunsetshimmer. It was because the tags are split on whether ssfoo or sunsetfoo is the variant, and this seemed like an opportunity to make them consistent. Again, sorry.

**Comment by Rothera** [comment]
Oh was that it. I usually go for the long name but if people add them after the fact I might not always notice. Or else I just messed up.

Could I trouble you to break this into two? One for `+v` fixes, one for the rest?

**Comment by nano23823** [comment]
Apologies for the delay on this, I've been buried irl. The PR is rebased, and I removed all edits that touched a variant tag. Is it mergeable now?

**Comment by Rothera** [comment]
Scrolled through. Obvious changes. Won't question it.

Actually, wow, you went through a *lot* of tags. I haven't paid attention to stuff like `+shrug` in a really long time.

**Pull request merged**
