### PR TITLE
Add missing +sillynumptie tags

### PR DESCRIPTION
**Pull request by Jibodeah**

### CODE REVIEW

**Comment by Shugabuga** [comment]
Seems harmless.

**Comment by Ajedi32** [comment]
Wouldn't you want it to be tagged `+sillynumptie` AND `+ocpony`? That's definitely still an OC.

**Comment by Jibodeah** [comment]
Hm. Probably. The ones in /r/SillyNumptie don't have that tag though so I thought I'd be consistent. (also it only occured after I'd committed)

**Comment by Shugabuga** [comment]
I'd add it to the /r/SillyNumptie emotes as well. Consistency, and it's an OC.

**Comment by Jibodeah** [comment]
I did!

**Comment by Shugabuga** [comment]
Showoff. /s

But seriously, looks good! Now we wait for Typhos to pull it. Idk when that would be though due to the recently passed holidays, though.

**Comment by Rothera** [comment]
For the record, `+sillynumptie` includes `+ocpony` already. (Various scripts will actually complain if you add that tag, since it's not needed.)

I added the tags in myself to avoid `+ocpony`.

**Pull request closed without merging**
